load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

expand_template(
    name = "config_h",
    out = "src/lib/libdwarf/config.h",
    substitutions = {
        "#cmakedefine AC_APPLE_UNIVERSAL_BUILD 1": "",
        "#cmakedefine CRAY_STACKSEG_END 1": "",
        "#cmakedefine HAVE_DLFCN_H 1": "#define HAVE_DLFCN_H 1",
        "#cmakedefine HAVE_FCNTL_H 1": "#define HAVE_FCNTL_H 1",
        "#cmakedefine WORDS_BIGENDIAN 1": "",
        "#cmakedefine HAVE_STDINT_H 1": "#define HAVE_STDINT_H 1",
        "#cmakedefine HAVE_SYS_STAT_H 1": "#define HAVE_SYS_STAT_H 1",
        "#cmakedefine HAVE_SYS_TYPES_H 1": "#define HAVE_SYS_TYPES_H 1",
        "#cmakedefine HAVE_FULL_MMAP 1": "#define HAVE_FULL_MMAP 1",
        "#cmakedefine uintptr_t  ${uintptr_t}": "",
        "#cmakedefine intptr_t  ${intptr_t}": "",
        "#cmakedefine HAVE_UNISTD_H 1": "#define HAVE_UNISTD_H 1",
        "#cmakedefine HAVE_ZLIB 1": "#define HAVE_ZLIB 1",
        "#cmakedefine HAVE_ZLIB_H 1": "#define HAVE_ZLIB_H 1",
        "#cmakedefine HAVE_ZSTD 1": "#define HAVE_ZSTD 1",
        "#cmakedefine HAVE_ZSTD_H 1": "#define HAVE_ZSTD_H 1",
        "#cmakedefine LT_OBJDIR 1": "",
        "#define PACKAGE_VERSION \"@PROJECT_VERSION@\"": "#define PACKAGE_VERSION \"0.12.0\"",
        "#define PACKAGE_BUGREPORT \"@PACKAGE_BUGREPORT@\"": "",
        "#define PACKAGE_NAME \"@PROJECT_NAME@\"": "",
        "#define PACKAGE_STRING \"@PACKAGE_STRING@\"": "",
        "#cmakedefine PACKAGE_TARNAME": "",
        "#define PACKAGE_URL \"@PROJECT_HOMEPAGE_URL@\"": "",
        "#cmakedefine STACK_DIRECTION": "",
        "#cmakedefine STDC_HEADERS 1": "#define STDC_HEADERS 1",
        "#cmakedefine PACKAGE_VERSION ${PACKAGE_VERSION}": "",
        # Must be substituted after all defines with a PACKAGE_* prefix,
        # otherwise it will replace part of those defines.
        "#cmakedefine PACKAGE": "",
    } | select({
        "@platforms//os:macos": {"#cmakedefine HAVE_MALLOC_H 1": ""},
        "//conditions:default": {"#cmakedefine HAVE_MALLOC_H 1": "#define HAVE_MALLOC_H 1"},
    }),
    template = "cmake/config.h.in",
)

cc_library(
    name = "dwarf",
    srcs = [":config_h"] + glob(
        [
            "src/lib/libdwarf/*.c",
            "src/lib/libdwarfp/*.c",
        ],
    ),
    hdrs = glob(
        [
            "src/lib/libdwarf/*.h",
            "src/lib/libdwarfp/*.h",
        ],
    ),
    includes = [
        "src/lib/libdwarf",
        "src/lib/libdwarfp",
    ],
    deps = [
        "@zlib",
        "@zstd",
    ],
)

alias(
    name = "libdwarf",
    actual = ":dwarf",
    visibility = ["//visibility:public"],
)

cc_test(
    name = "canonical_test",
    srcs = ["test/test_canonical.c"],
    deps = [
        ":dwarf",
    ],
)
